server.port=8888
spring.application.name=config-server

# Point this to a folder on your computer where you will keep .properties files for other services
spring.cloud.config.server.git.uri=file:///D:/GDSE ASSIGNMENTS/18.Cloud Architecture/ecoride-config-repo